# permissions for end users to edit apigws.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: apigw-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: apigw-operator
    app.kubernetes.io/part-of: apigw-operator
    app.kubernetes.io/managed-by: kustomize
  name: apigw-editor-role
rules:
- apiGroups:
  - operator.digitalhub.it
  resources:
  - apigws
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - operator.digitalhub.it
  resources:
  - apigws/status
  verbs:
  - get
