# permissions for end users to view apigws.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: apigw-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: apigw-operator
    app.kubernetes.io/part-of: apigw-operator
    app.kubernetes.io/managed-by: kustomize
  name: apigw-viewer-role
rules:
- apiGroups:
  - operator.scc-digitalhub.github.io
  resources:
  - apigws
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - operator.scc-digitalhub.github.io
  resources:
  - apigws/status
  verbs:
  - get
