apiVersion: operator.scc-digitalhub.github.io/v1
kind: ApiGw
metadata:
  name: apigw-sample
  namespace: apigw-operator-system
spec:
  host: foo.bar.com
  path: /
  service: productpage
  port: 9080
  auth:
    type: basic
    basic:
      user: user
      password: password